# Generated by Django 5.1.1 on 2024-09-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='author',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='title',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
    ]
