# Generated by Django 5.1.1 on 2024-09-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookmark_unique_together_bookmark_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
